require('dotenv').config();
const express=require('express'); const cors=require('cors'); const helmet=require('helmet'); const http=require('http'); const WebSocket=require('ws'); const path=require('path'); const crypto=require('crypto');
const {JsonStore}=require('./store'); const {decide}=require('./openai'); const {TelegramBridge}=require('./telegram');
const PORT=Number(process.env.PORT||8080); const DATA_PATH=process.env.DATA_PATH||path.join(__dirname,'../data/store.json'); const API_KEY=process.env.EXTENSION_API_KEY||'change-me';
const store=new JsonStore(DATA_PATH); const app=express(); app.use(helmet({contentSecurityPolicy:false})); app.use(cors()); app.use(express.json({limit:'3mb'}));
const server=http.createServer(app); const wss=new WebSocket.Server({server,path:'/ws'}); const devices=new Map();
function auth(req,res,next){const k=req.headers['x-api-key']||req.query.key;if(k!==API_KEY)return res.status(401).json({ok:false,error:'unauthorized'});next();}
function sendToDevice(deviceId,payload){const ws=devices.get(deviceId);if(!ws||ws.readyState!==WebSocket.OPEN)return false;ws.send(JSON.stringify(payload));return true;}
wss.on('connection',(ws,req)=>{const url=new URL(req.url,'http://localhost');if(url.searchParams.get('key')!==API_KEY){ws.close(1008,'unauthorized');return;}const id=url.searchParams.get('deviceId')||crypto.randomUUID();devices.set(id,ws);ws.send(JSON.stringify({type:'hello',deviceId:id,settings:store.data.settings}));ws.on('close',()=>devices.delete(id));ws.on('message',raw=>{try{const m=JSON.parse(raw);if(m.type==='send_result'){const c=store.data.cases[m.caseId];if(c){c.status=m.ok?'sent':'failed';c.error=m.error||null;c.sentAt=new Date().toISOString();store.save();telegram.confirm(`${m.ok?'✅':'❌'} ${m.ok?'Balasan berhasil dikirim':'Balasan gagal dikirim'}\nKasus: ${m.caseId}\nMember: ${c.memberName||'-'}${m.error?`\nError: ${m.error}`:''}`)}}}catch{}});});
const telegram=new TelegramBridge({store,onReply:async(c,text)=>{const ok=sendToDevice(c.deviceId,{type:'telegram_reply',caseId:c.id,conversationId:c.conversationId,memberId:c.memberId,reply:text});if(!ok){c.status='waiting_device';store.save();await telegram.confirm(`⚠️ Extension ${c.deviceId} sedang offline. Balasan kasus ${c.id} disimpan dan akan dikirim saat perangkat aktif.`);}}}); telegram.start();
app.get('/health',(req,res)=>res.json({ok:true,service:'livechat-ai-bot',devices:devices.size,openaiReady:!!process.env.OPENAI_API_KEY,telegramReady:!!process.env.TELEGRAM_BOT_TOKEN,time:new Date().toISOString()}));
app.post('/api/analyze',auth,async(req,res)=>{try{const {deviceId,conversationId,memberId,memberName,userId,history=[],lastMessageId,isNewChat=false}=req.body;if(!deviceId||!conversationId||!lastMessageId)return res.status(400).json({ok:false,error:'missing identifiers'});const dedupe=`${conversationId}:${lastMessageId}`;if(store.data.handledMessages[dedupe])return res.json({ok:true,action:'skip',reason:'already_handled'});
const decision=await decide({history,knowledge:store.data.knowledge});
if(decision.requires_telegram || decision.confidence < Number(store.data.settings.confidenceThreshold||.86)){
 const id=`AI-${Date.now().toString(36).toUpperCase()}`; const c={id,type:decision.intent,deviceId,conversationId,memberId,memberName,userId,lastMessage:history.at(-1)?.text||'',summary:decision.summary,status:'waiting_telegram',createdAt:new Date().toISOString(),history};store.data.cases[id]=c;store.data.handledMessages[dedupe]={status:'waiting_telegram',caseId:id};store.save();await telegram.notifyCase(c);return res.json({ok:true,action:'wait_telegram',caseId:id});}
store.data.handledMessages[dedupe]={status:'reply_ready',at:new Date().toISOString()};store.save();res.json({ok:true,action:'reply',reply:decision.reply,shouldClose:!!decision.should_close_chat,intent:decision.intent,confidence:decision.confidence,source:decision.source});
}catch(e){console.error(e);res.status(500).json({ok:false,error:e.message});}});
app.post('/api/learn',auth,(req,res)=>{const {example,answer,intent='learned',source='cs'}=req.body;if(!example||!answer)return res.status(400).json({ok:false,error:'example and answer required'});store.data.knowledge.push({id:crypto.randomUUID(),example,answer,intent,source,approved:true,createdAt:new Date().toISOString()});store.save();res.json({ok:true});});
app.get('/api/settings',auth,(req,res)=>res.json({ok:true,settings:store.data.settings,knowledgeCount:store.data.knowledge.length,cases:Object.values(store.data.cases).slice(-100),devices:[...devices.keys()]}));
app.post('/api/settings',auth,(req,res)=>{Object.assign(store.data.settings,req.body||{});store.save();for(const ws of devices.values()) if(ws.readyState===WebSocket.OPEN) ws.send(JSON.stringify({type:'settings',settings:store.data.settings}));res.json({ok:true,settings:store.data.settings});});
app.get('/',(req,res)=>res.type('html').send(`<!doctype html><meta charset=utf-8><title>LiveChat AI Bot</title><style>body{font-family:Arial;max-width:900px;margin:40px auto;padding:0 20px}code{background:#eee;padding:3px 6px}</style><h1>LiveChat AI Bot</h1><p>Server aktif.</p><p>Health: <a href=/health>/health</a></p><p>Perangkat online: ${devices.size}</p>`));
server.listen(PORT,()=>console.log(`Server running on ${PORT}`));
